"""
FPL IQL Policy — single self-contained file
============================================
Implements the required StudentPolicy interface:
    fit(train_data)  - train reward model + IQL on historical data
    reset()          -  reset per-rollout state
    act(state)       -  return list of transfers [(player_out, player_in), ...]

Strategy: Implicit Q-Learning (Kostrikov et al., ICLR 2022)
  1. HistGradientBoosting reward model predicts player points from
     14 hand-crafted rolling features per player per gameweek.
  2. An offline replay buffer is generated by running epsilon-greedy
     rollouts on the training data using the reward model as simulator.
  3. IQL (V-net + Q-net with expectile value loss) is trained on the buffer.
  4. At inference, valid transfers are scored by the Q-network and the best
     one is returned (with a no-transfer baseline).

Dependencies: numpy, pandas, torch, scikit-learn  (all standard / pip-installable)
"""

import numpy as np
import pandas as pd
from typing import Dict, List, Optional, Tuple, Union

import torch
import torch.nn as nn
import torch.optim as optim

from sklearn.ensemble import HistGradientBoostingRegressor
from sklearn.model_selection import KFold
from sklearn.metrics import mean_absolute_error


# ===========================================================================
# ── SECTION 1: Feature Engineering ─────────────────────────────────────────
# ===========================================================================

POSITION_ENC = {"GK": 0, "DEF": 1, "MID": 2, "FWD": 3}

FEATURE_COLS = [
    "price",            # 0  – player price in £M
    "form_3gw",         # 1  – rolling avg total_points last 3 GWs
    "form_5gw",         # 2  – rolling avg total_points last 5 GWs
    "minutes_form_3gw", # 3  – rolling avg minutes last 3 GWs
    "goals_3gw",        # 4  – goals scored last 3 GWs
    "assists_3gw",      # 5  – assists last 3 GWs
    "clean_sheets_3gw", # 6  – clean sheets last 3 GWs
    "starts_pct_3gw",   # 7  – fraction of last 3 GWs started (>45 min)
    "xP",               # 8  – expected points (provided in data)
    "was_home",         # 9  – home fixture flag
    "opp_strength",     # 10 – normalised opponent difficulty [0,1]
    "position_enc",     # 11 – ordinal position {GK:0, DEF:1, MID:2, FWD:3}
    "bonus_3gw",        # 12 – bonus points last 3 GWs
    "bps_3gw",          # 13 – avg BPS last 3 GWs
]

N_FEATURES = len(FEATURE_COLS)   # 14
STATE_DIM  = 2 + 15 * N_FEATURES # 212
ACTION_DIM = 11

FeatureCache = Dict  # type alias


def _build_features(df: pd.DataFrame) -> pd.DataFrame:
    """Enrich raw merged_gw DataFrame with engineered FEATURE_COLS."""
    df = df.copy()
    if "GW" not in df.columns:
        df["GW"] = df["round"] if "round" in df.columns else 1

    for col in ["value", "total_points", "minutes", "goals_scored", "assists",
                "clean_sheets", "saves", "bonus", "bps", "goals_conceded"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0)

    df["xP"]          = pd.to_numeric(df.get("xP", 0), errors="coerce").fillna(0)
    df["was_home"]    = df["was_home"].astype(int) if "was_home" in df.columns else 0
    df["price"]       = df["value"] / 10.0
    df["position_enc"] = df["position"].map(POSITION_ENC).fillna(0).astype(int)

    df = df.sort_values(["element", "GW"]).reset_index(drop=True)
    grp = df.groupby("element", sort=False)

    def roll_mean(col, n):
        return grp[col].transform(
            lambda x: x.shift(1).rolling(n, min_periods=1).mean()
        ).fillna(0)

    def roll_sum(col, n):
        return grp[col].transform(
            lambda x: x.shift(1).rolling(n, min_periods=1).sum()
        ).fillna(0)

    df["form_3gw"]         = roll_mean("total_points", 3)
    df["form_5gw"]         = roll_mean("total_points", 5)
    df["minutes_form_3gw"] = roll_mean("minutes", 3)
    df["goals_3gw"]        = roll_sum("goals_scored", 3)
    df["assists_3gw"]      = roll_sum("assists", 3)
    df["clean_sheets_3gw"] = roll_sum("clean_sheets", 3)
    df["bonus_3gw"]        = roll_sum("bonus", 3)
    df["bps_3gw"]          = roll_mean("bps", 3)
    df["started"]          = (df["minutes"] > 45).astype(float)
    df["starts_pct_3gw"]   = roll_mean("started", 3)

    if "opponent_team" in df.columns and "goals_conceded" in df.columns:
        opp_raw = df.groupby("opponent_team")["goals_conceded"].mean()
        mn, mx  = opp_raw.min(), opp_raw.max()
        rng     = mx - mn if mx != mn else 1.0
        df["opp_strength"] = df["opponent_team"].map(
            ((opp_raw - mn) / rng).to_dict()
        ).fillna(0.5)
    else:
        df["opp_strength"] = 0.5

    return df


def _build_feature_cache(feature_df: pd.DataFrame) -> FeatureCache:
    """Build O(1) lookup: {(element, gw) -> feature_vector}."""
    exact: Dict[Tuple[int, int], np.ndarray] = {}
    latest: Dict[int, np.ndarray] = {}
    position: Dict[int, str] = {}
    team: Dict[int, str] = {}
    zero = np.zeros(N_FEATURES, dtype=np.float32)

    for _, row in feature_df.sort_values(["element", "GW"]).iterrows():
        eid = int(row["element"])
        gw  = int(row["GW"])
        feats = np.array(
            [float(row.get(c, 0.0) or 0.0) for c in FEATURE_COLS],
            dtype=np.float32,
        )
        exact[(eid, gw)] = feats
        latest[eid] = feats
        if eid not in position:
            position[eid] = str(row.get("position", "MID"))
            team[eid]     = str(row.get("team", ""))

    return {"exact": exact, "latest": latest, "position": position,
            "team": team, "zero": zero}


def _get_feats(cache: FeatureCache, pid: int, gw: int) -> np.ndarray:
    """O(1) feature lookup with nearest-earlier-GW fallback."""
    key = (pid, gw)
    if key in cache["exact"]:
        return cache["exact"][key]
    for g in range(gw - 1, 0, -1):
        k = (pid, g)
        if k in cache["exact"]:
            return cache["exact"][k]
    return cache["latest"].get(pid, cache["zero"]).copy()


def _pos_map(cache: FeatureCache, squad: List[int]) -> Dict[str, List[int]]:
    pm: Dict[str, List[int]] = {"GK": [], "DEF": [], "MID": [], "FWD": []}
    for pid in squad:
        p = cache["position"].get(pid, "MID")
        pm[p if p in pm else "MID"].append(pid)
    return pm


def _count_teams(squad: List[int], player_team: Dict[int, str]) -> Dict[str, int]:
    counts: Dict[str, int] = {}
    for pid in squad:
        t = player_team.get(pid, "")
        counts[t] = counts.get(t, 0) + 1
    return counts


def _build_state_vec(squad: List[int], gw: int, budget: float,
                     cache: FeatureCache, max_gw: int = 38) -> np.ndarray:
    """212-dim state: [gw_norm, budget_norm, 15×14 player features]."""
    pf  = {pid: _get_feats(cache, pid, gw) for pid in squad}
    pm  = _pos_map(cache, squad)
    gks  = sorted(pm["GK"],  key=lambda p: -pf[p][1])
    defs = sorted(pm["DEF"], key=lambda p: -pf[p][1])
    mids = sorted(pm["MID"], key=lambda p: -pf[p][1])
    fwds = sorted(pm["FWD"], key=lambda p: -pf[p][1])
    z = np.zeros(N_FEATURES, dtype=np.float32)
    slots = [("GK", 2, gks), ("DEF", 5, defs), ("MID", 5, mids), ("FWD", 3, fwds)]
    parts = [np.array([gw / max_gw, np.clip(budget / 100.0, 0, 1)], dtype=np.float32)]
    for _, n, players in slots:
        for i in range(n):
            parts.append(pf[players[i]] if i < len(players) else z)
    return np.concatenate(parts)


def _build_action_vec(p_out: int, p_in: int, gw: int, cache: FeatureCache,
                      budget: float, no_transfer: bool = False) -> np.ndarray:
    """11-dim action vector."""
    if no_transfer:
        return np.zeros(ACTION_DIM, dtype=np.float32)
    fo = _get_feats(cache, p_out, gw)
    fi = _get_feats(cache, p_in,  gw)
    dp = fi[1] - fo[1]
    dv = fo[0] - fi[0]
    return np.array([
        1.0,
        fo[11] / 3.0, fi[11] / 3.0,
        fo[1]  / 15.0, fo[0] / 15.0,
        fi[1]  / 15.0, fi[0] / 15.0,
        dp     / 15.0,
        dv     / 10.0,
        np.clip((budget + dv) / 100.0, -1.0, 1.0),
        float(fo[11] == fi[11]),
    ], dtype=np.float32)


# ===========================================================================
# ── SECTION 2: Reward Model ──────────────────────────────────────────────────
# ===========================================================================

class _PointsPredictor:
    """
    HistGradientBoostingRegressor wrapper predicting total_points
    from FEATURE_COLS.  Cross-validates for MAE reporting, then trains
    a final model on all data.
    """

    def __init__(self):
        self.model: Optional[HistGradientBoostingRegressor] = None
        self._mean: float = 2.0

    def fit(self, feature_df: pd.DataFrame, verbose: bool = False) -> dict:
        df = feature_df.dropna(subset=["total_points"])
        X = df[FEATURE_COLS].fillna(0.0).astype(np.float32).values
        y = df["total_points"].values.astype(np.float32)
        self._mean = float(np.mean(y))

        cv_params = dict(max_iter=400, learning_rate=0.05, max_leaf_nodes=63,
                         max_depth=6, min_samples_leaf=20, l2_regularization=0.1,
                         random_state=42, early_stopping=True,
                         validation_fraction=0.1, n_iter_no_change=30, verbose=0)

        kf = KFold(n_splits=5, shuffle=True, random_state=42)
        oof = np.zeros(len(y))
        for _, (tr, va) in enumerate(kf.split(X)):
            m = HistGradientBoostingRegressor(**cv_params)
            m.fit(X[tr], y[tr])
            oof[va] = m.predict(X[va])
        cv_mae = mean_absolute_error(y, oof)

        self.model = HistGradientBoostingRegressor(
            max_iter=400, learning_rate=0.05, max_leaf_nodes=63,
            max_depth=6, min_samples_leaf=20, l2_regularization=0.1,
            random_state=42, early_stopping=False,
        )
        self.model.fit(X, y)

        if verbose:
            print(f"[PointsPredictor] CV MAE={cv_mae:.4f}  mean_pts={self._mean:.2f}")
        return {"cv_mae": cv_mae, "mean_points": self._mean}

    def predict_batch(self, X: np.ndarray) -> np.ndarray:
        if self.model is None:
            return np.full(len(X), self._mean)
        return np.maximum(0.0, self.model.predict(X.astype(np.float32)))

    def predict_one(self, feats: np.ndarray) -> float:
        return float(self.predict_batch(feats.reshape(1, -1))[0])


# ===========================================================================
# ── SECTION 3: FPL Environment ───────────────────────────────────────────────
# ===========================================================================

_POSITION_COUNTS = {"GK": 2, "DEF": 5, "MID": 5, "FWD": 3}
_TOTAL_BUDGET    = 100.0
_MAX_PER_CLUB    = 3
_TRANSFER_PENALTY = 4.0


class _FPLEnv:
    """Full FPL simulation environment (15-player squad, budget, club limits)."""

    def __init__(self, feature_df: pd.DataFrame, predictor: _PointsPredictor,
                 cache: FeatureCache, noise_std: float = 1.0, seed: int = 42):
        self.feature_df = feature_df
        self.predictor  = predictor
        self.cache      = cache
        self.noise_std  = noise_std
        self.rng        = np.random.default_rng(seed)

        self.all_gws = sorted(feature_df["GW"].unique())
        self.min_gw  = self.all_gws[0]
        self.max_gw  = self.all_gws[-1]

        self.player_position = cache["position"]
        self.player_team     = cache["team"]

        self.players_by_pos: Dict[str, List[int]] = {
            "GK": [], "DEF": [], "MID": [], "FWD": []
        }
        for pid, pos in self.player_position.items():
            if pos in self.players_by_pos:
                self.players_by_pos[pos].append(pid)

        self._cand_cache: Dict[Tuple[str, int], List[int]] = {}
        self._price: Dict[Tuple[int, int], float] = {}
        for _, row in feature_df.iterrows():
            self._price[(int(row["element"]), int(row["GW"]))] = float(row["price"])

        self.squad: List[int] = []
        self.budget: float    = 0.0
        self.gw: int          = self.min_gw

    def get_price(self, pid: int, gw: int) -> float:
        k = (pid, gw)
        if k in self._price:
            return self._price[k]
        for off in range(1, 10):
            for d in (-off, off):
                k2 = (pid, gw + d)
                if k2 in self._price:
                    return self._price[k2]
        return 5.0

    def reset(self, squad: Optional[List[int]] = None) -> Tuple:
        self.gw = self.min_gw
        self.squad = list(squad) if squad else self._random_squad(self.gw)
        self.budget = max(0.0, _TOTAL_BUDGET - sum(
            self.get_price(p, self.gw) for p in self.squad
        ))
        return (self.gw, tuple(self.squad))

    def step(self, action) -> Tuple[Tuple, float, bool]:
        transfers = ([action] if isinstance(action, tuple) else
                     action   if isinstance(action, list) else [])
        penalty = 0.0
        for p_out, p_in in transfers:
            if p_out not in self.squad:
                continue
            po = self.get_price(p_out, self.gw)
            pi = self.get_price(p_in,  self.gw)
            if pi > po + self.budget + 0.01:
                continue
            self.squad = [p_in if p == p_out else p for p in self.squad]
            self.budget += po - pi
            penalty += _TRANSFER_PENALTY  # always 1 free transfer used
        # correct: first transfer is free, only additional ones cost -4
        # re-compute: if transfers ≤ 1, no penalty
        if len(transfers) <= 1:
            penalty = 0.0
        else:
            penalty = (len(transfers) - 1) * _TRANSFER_PENALTY

        X = np.array([_get_feats(self.cache, p, self.gw) for p in self.squad],
                     dtype=np.float32)
        preds = self.predictor.predict_batch(X)
        reward = float(preds.sum())
        if self.noise_std > 0:
            reward += np.random.normal(0, self.noise_std * np.sqrt(len(self.squad)))
        reward = max(0.0, reward) - penalty

        self.gw += 1
        done = self.gw > self.max_gw
        return (self.gw, tuple(self.squad)), reward, done

    def get_valid_actions(self, squad: List[int], gw: int,
                          budget: float, max_cand: int = 30) -> List:
        actions   = [None]
        squad_set = set(squad)
        pm        = _pos_map(self.cache, squad)
        tc        = _count_teams(squad, self.player_team)
        for pos, out_players in pm.items():
            cands = self._candidates(pos, squad_set, gw, max_cand)
            for p_out in out_players:
                po      = self.get_price(p_out, gw)
                team_out = self.player_team.get(p_out, "")
                for p_in in cands:
                    pi = self.get_price(p_in, gw)
                    if pi > po + budget + 0.01:
                        continue
                    team_in = self.player_team.get(p_in, "")
                    adj = (tc.get(team_in, 0)
                           + (-1 if team_in == team_out else 0) + 1)
                    if adj > _MAX_PER_CLUB:
                        continue
                    actions.append((p_out, p_in))
        return actions

    def _candidates(self, pos: str, squad_set: set, gw: int, max_n: int) -> List[int]:
        key = (pos, gw)
        if key not in self._cand_cache:
            scored = [(  _get_feats(self.cache, pid, gw)[1], pid)
                      for pid in self.players_by_pos.get(pos, [])]
            scored.sort(reverse=True)
            self._cand_cache[key] = [p for _, p in scored]
        return [p for p in self._cand_cache[key] if p not in squad_set][:max_n]

    def _random_squad(self, gw: int) -> List[int]:
        budget = _TOTAL_BUDGET
        squad: List[int] = []
        tc: Dict[str, int] = {}
        for pos, n in _POSITION_COUNTS.items():
            avail = self.players_by_pos.get(pos, []).copy()
            self.rng.shuffle(avail)
            added = 0
            for pid in avail:
                if added >= n:
                    break
                if pid in squad:
                    continue
                pr  = self.get_price(pid, gw)
                tm  = self.player_team.get(pid, "")
                if tc.get(tm, 0) >= _MAX_PER_CLUB or pr > budget:
                    continue
                squad.append(pid); budget -= pr
                tc[tm] = tc.get(tm, 0) + 1; added += 1
            for pid in avail:
                if added >= n:
                    break
                if pid not in squad:
                    squad.append(pid)
                    tc[self.player_team.get(pid, "")] = (
                        tc.get(self.player_team.get(pid, ""), 0) + 1)
                    added += 1
        return squad[:15]


def _collect_offline_data(env: _FPLEnv, n_rollouts: int, epsilon: float,
                          max_cand: int, seed: int) -> List[dict]:
    """Epsilon-greedy rollouts → list of (s, a, r, s', done) dicts."""
    rng  = np.random.default_rng(seed)
    data = []
    for _ in range(n_rollouts):
        state = env.reset()
        done  = False
        while not done:
            gw, squad = state
            budget = env.budget
            actions = env.get_valid_actions(list(squad), gw, budget, max_cand)
            if rng.random() < epsilon or len(actions) == 1:
                action = actions[int(rng.integers(len(actions)))]
            else:
                action = _greedy(actions, gw, env.cache)
            s_vec = _build_state_vec(list(squad), gw, budget, env.cache,
                                     env.max_gw)
            a_vec = (_build_action_vec(0, 0, gw, env.cache, budget,
                                       no_transfer=True)
                     if action is None else
                     _build_action_vec(action[0], action[1], gw, env.cache,
                                       budget))
            next_state, reward, done = env.step(action)
            ng, ns = next_state
            sn_vec = _build_state_vec(list(ns), ng, env.budget, env.cache,
                                      env.max_gw)
            data.append({"s": s_vec, "a": a_vec, "r": float(reward),
                         "s_next": sn_vec, "done": float(done)})
            state = next_state
    return data


def _greedy(actions, gw: int, cache: FeatureCache):
    best, score = None, -np.inf
    for a in actions:
        s = (0.0 if a is None else
             (_get_feats(cache, a[1], gw)[1] + _get_feats(cache, a[1], gw)[8])
             - (_get_feats(cache, a[0], gw)[1] + _get_feats(cache, a[0], gw)[8]))
        if s > score:
            score, best = s, a
    return best


# ===========================================================================
# ── SECTION 4: IQL Networks & Training ───────────────────────────────────────
# ===========================================================================

class _MLP(nn.Module):
    def __init__(self, in_dim: int, hidden: int, out_dim: int = 1):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(in_dim, hidden), nn.LayerNorm(hidden), nn.ReLU(),
            nn.Linear(hidden, hidden), nn.LayerNorm(hidden), nn.ReLU(),
            nn.Linear(hidden, out_dim),
        )

    def forward(self, x):
        return self.net(x)


class _VNet(nn.Module):
    def __init__(self, sdim: int, hidden: int):
        super().__init__()
        self.net = _MLP(sdim, hidden)

    def forward(self, s):
        return self.net(s).squeeze(-1)


class _QNet(nn.Module):
    def __init__(self, sdim: int, adim: int, hidden: int):
        super().__init__()
        self.net = _MLP(sdim + adim, hidden)

    def forward(self, s, a):
        return self.net(torch.cat([s, a], dim=-1)).squeeze(-1)


class _ReplayBuffer:
    def __init__(self, transitions: List[dict], device: torch.device):
        n    = len(transitions)
        sdim = transitions[0]["s"].shape[0]
        adim = transitions[0]["a"].shape[0]
        self.s      = torch.zeros(n, sdim, device=device)
        self.a      = torch.zeros(n, adim, device=device)
        self.r      = torch.zeros(n, device=device)
        self.s_next = torch.zeros(n, sdim, device=device)
        self.done   = torch.zeros(n, device=device)
        for i, t in enumerate(transitions):
            self.s[i]      = torch.from_numpy(t["s"])
            self.a[i]      = torch.from_numpy(t["a"])
            self.r[i]      = t["r"]
            self.s_next[i] = torch.from_numpy(t["s_next"])
            self.done[i]   = t["done"]
        self.n = n; self.device = device
        # normalise rewards
        mu = self.r.mean(); sg = self.r.std().clamp(min=1e-6)
        self.r = (self.r - mu) / sg

    def sample(self, bs: int):
        idx = torch.randint(0, self.n, (bs,), device=self.device)
        return self.s[idx], self.a[idx], self.r[idx], self.s_next[idx], self.done[idx]


def _expectile_loss(diff: torch.Tensor, tau: float) -> torch.Tensor:
    """Lτ²(u) = |τ − 𝟙(u<0)| · u²"""
    w = torch.where(diff >= 0, torch.full_like(diff, tau),
                    torch.full_like(diff, 1.0 - tau))
    return (w * diff.pow(2)).mean()


class _IQLAgent:
    """
    Implicit Q-Learning (Kostrikov et al., ICLR 2022).

    L_V = E[Lτ²(Q(s,a) − V(s))]           (expectile regression)
    L_Q = E[(r + γ·V(s') − Q(s,a))²]       (TD error)
    π   = argmax_a Q(s, a)                  (greedy extraction)
    """

    def __init__(self, sdim: int, adim: int, hidden: int = 256,
                 gamma: float = 0.99, tau: float = 0.7, lr: float = 3e-4,
                 device: Optional[torch.device] = None):
        self.gamma = gamma; self.tau = tau
        self.device = device or torch.device(
            "cuda" if torch.cuda.is_available() else "cpu")

        self.v_net   = _VNet(sdim, hidden).to(self.device)
        self.q_net   = _QNet(sdim, adim, hidden).to(self.device)
        self.q_tgt   = _QNet(sdim, adim, hidden).to(self.device)
        self.q_tgt.load_state_dict(self.q_net.state_dict())
        for p in self.q_tgt.parameters():
            p.requires_grad = False

        self.v_opt = optim.Adam(self.v_net.parameters(), lr=lr)
        self.q_opt = optim.Adam(self.q_net.parameters(), lr=lr)

    def _step(self, s, a, r, sn, done, polyak=0.005):
        with torch.no_grad():
            q_tgt_val = r + self.gamma * (1 - done) * self.v_net(sn)
        q_pred = self.q_net(s, a)
        q_loss = nn.functional.mse_loss(q_pred, q_tgt_val)
        self.q_opt.zero_grad(); q_loss.backward()
        nn.utils.clip_grad_norm_(self.q_net.parameters(), 1.0)
        self.q_opt.step()

        with torch.no_grad():
            q_val = self.q_net(s, a)
        v_pred = self.v_net(s)
        v_loss = _expectile_loss(q_val - v_pred, self.tau)
        self.v_opt.zero_grad(); v_loss.backward()
        nn.utils.clip_grad_norm_(self.v_net.parameters(), 1.0)
        self.v_opt.step()

        for p, tp in zip(self.q_net.parameters(), self.q_tgt.parameters()):
            tp.data.mul_(1 - polyak).add_(p.data, alpha=polyak)

        return q_loss.item(), v_loss.item(), q_pred.mean().item()

    def train(self, buf: _ReplayBuffer, n_steps: int, batch_size: int,
              log_interval: int = 5000, verbose: bool = True):
        rq = rv = rqm = 0.0
        for step in range(1, n_steps + 1):
            ql, vl, qm = self._step(*buf.sample(batch_size))
            rq += ql; rv += vl; rqm += qm
            if step % log_interval == 0 and verbose:
                print(f"[IQL {step:>6}] Q_loss={rq/log_interval:.4f}  "
                      f"V_loss={rv/log_interval:.4f}  Q_mean={rqm/log_interval:.3f}")
                rq = rv = rqm = 0.0

    @torch.no_grad()
    def score(self, s_vec: np.ndarray, a_vecs: List[np.ndarray]) -> np.ndarray:
        s = torch.from_numpy(s_vec).float().to(self.device)
        A = torch.from_numpy(np.stack(a_vecs)).float().to(self.device)
        S = s.unsqueeze(0).expand(len(a_vecs), -1)
        return self.q_net(S, A).cpu().numpy()


# ===========================================================================
# ── SECTION 5: StudentPolicy ─────────────────────────────────────────────────
# ===========================================================================

N_ROLLOUTS    = 150
EPSILON       = 0.30
MAX_CAND      = 30
IQL_STEPS     = 25_000
BATCH_SIZE    = 256
GAMMA         = 0.99
TAU_EXPECTILE = 0.7
LR            = 3e-4
HIDDEN        = 256
LOG_INTERVAL  = 5000


class StudentPolicy:
    """
    IQL-based FPL policy.

    fit(train_data):
        Trains a HistGBM reward model then an IQL agent from offline
        epsilon-greedy rollouts on the provided historical data.

    reset():
        Resets per-rollout budget tracking (call before each new episode).

    act(state):
        state = (gameweek: int, squad: tuple[int, ...])
        Returns a list of at most one transfer [(player_out_id, player_in_id)]
        or [] for no transfer.  Respects budget, positional composition,
        and the 3-players-per-club rule.
    """

    def __init__(self):
        self._predictor:  Optional[_PointsPredictor] = None
        self._iql:        Optional[_IQLAgent]         = None
        self._cache:      Optional[FeatureCache]       = None
        self._price_dict: Dict[Tuple[int, int], float] = {}
        self._by_pos:     Dict[str, List[int]]         = {
            "GK": [], "DEF": [], "MID": [], "FWD": []
        }
        self._max_gw: int   = 38
        self._budget: float = 0.0
        self._last_squad: Optional[tuple] = None
        self._init: bool = False

    # -----------------------------------------------------------------------
    def fit(self, train_data: pd.DataFrame) -> None:
        """Train reward model and IQL agent on historical FPL data."""
        print("[StudentPolicy] Building features...")
        feat_df = _build_features(train_data)
        self._max_gw = int(feat_df["GW"].max())

        print("[StudentPolicy] Building feature cache...")
        self._cache = _build_feature_cache(feat_df)
        for _, row in feat_df.iterrows():
            self._price_dict[(int(row["element"]), int(row["GW"]))] = float(
                row["price"])
        for pos in ["GK", "DEF", "MID", "FWD"]:
            self._by_pos[pos] = [
                pid for pid, p in self._cache["position"].items() if p == pos
            ]

        print("[StudentPolicy] Training reward model...")
        self._predictor = _PointsPredictor()
        stats = self._predictor.fit(feat_df, verbose=True)
        print(f"[StudentPolicy] CV MAE={stats['cv_mae']:.4f}")

        print(f"[StudentPolicy] Collecting offline data ({N_ROLLOUTS} rollouts)...")
        env = _FPLEnv(feat_df, self._predictor, self._cache,
                      noise_std=1.0, seed=0)
        transitions = _collect_offline_data(
            env, n_rollouts=N_ROLLOUTS, epsilon=EPSILON,
            max_cand=MAX_CAND, seed=42,
        )
        print(f"[StudentPolicy] Collected {len(transitions)} transitions.")

        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        print(f"[StudentPolicy] Training IQL on {device} for {IQL_STEPS} steps...")
        buf = _ReplayBuffer(transitions, device)
        self._iql = _IQLAgent(STATE_DIM, ACTION_DIM, HIDDEN, GAMMA,
                               TAU_EXPECTILE, LR, device)
        self._iql.train(buf, IQL_STEPS, BATCH_SIZE, LOG_INTERVAL, verbose=True)
        print("[StudentPolicy] fit() complete.")

    # -----------------------------------------------------------------------
    def reset(self) -> None:
        self._budget     = 0.0
        self._last_squad = None
        self._init       = False

    # -----------------------------------------------------------------------
    def act(self, state) -> List[Tuple[int, int]]:
        if self._cache is None or self._iql is None:
            return []

        gw, squad_tuple = state
        gw    = int(gw)
        squad = list(squad_tuple)

        if not self._init:
            cost = sum(self._price(p, gw) for p in squad)
            self._budget = max(0.0, _TOTAL_BUDGET - cost)
            self._init   = True
        elif self._last_squad is not None and set(squad_tuple) != set(self._last_squad):
            cost = sum(self._price(p, gw) for p in squad)
            self._budget = max(0.0, _TOTAL_BUDGET - cost)
        self._last_squad = squad_tuple

        actions = self._valid_actions(squad, gw)
        if len(actions) <= 1:
            return []

        s_vec = _build_state_vec(squad, gw, self._budget, self._cache,
                                 self._max_gw)
        a_vecs = [
            (_build_action_vec(0, 0, gw, self._cache, self._budget,
                               no_transfer=True)
             if a is None else
             _build_action_vec(a[0], a[1], gw, self._cache, self._budget))
            for a in actions
        ]
        q_scores = self._iql.score(s_vec, a_vecs)

        no_tr_score = q_scores[next(i for i, a in enumerate(actions) if a is None)]
        best_idx    = int(np.argmax(q_scores))
        best        = actions[best_idx]

        if best is None or q_scores[best_idx] <= no_tr_score + 0.01:
            return []

        p_out, p_in = best
        self._budget += self._price(p_out, gw) - self._price(p_in, gw)
        return [best]

    # -----------------------------------------------------------------------
    def predict_reward(self, player_dict: dict) -> float:
        """Predict reward for a player given a feature dict (evaluation helper)."""
        if self._predictor is None:
            return 2.0
        feats = np.array(
            [float(player_dict.get(c, 0.0) or 0.0) for c in FEATURE_COLS],
            dtype=np.float32,
        )
        return self._predictor.predict_one(feats)

    # -----------------------------------------------------------------------
    # Internal helpers
    # -----------------------------------------------------------------------

    def _price(self, pid: int, gw: int) -> float:
        k = (pid, gw)
        if k in self._price_dict:
            return self._price_dict[k]
        for off in range(1, 10):
            for d in (-off, off):
                k2 = (pid, gw + d)
                if k2 in self._price_dict:
                    return self._price_dict[k2]
        return 5.0

    def _valid_actions(self, squad: List[int], gw: int) -> List:
        actions   = [None]
        squad_set = set(squad)
        pm        = _pos_map(self._cache, squad)
        tc        = _count_teams(squad, self._cache["team"])
        for pos, out_players in pm.items():
            cands = self._candidates(pos, squad_set, gw)
            for p_out in out_players:
                po      = self._price(p_out, gw)
                team_out = self._cache["team"].get(p_out, "")
                for p_in in cands:
                    pi = self._price(p_in, gw)
                    if pi > po + self._budget + 0.01:
                        continue
                    team_in = self._cache["team"].get(p_in, "")
                    adj = (tc.get(team_in, 0)
                           + (-1 if team_in == team_out else 0) + 1)
                    if adj > _MAX_PER_CLUB:
                        continue
                    actions.append((p_out, p_in))
        return actions

    def _candidates(self, pos: str, squad_set: set, gw: int,
                    max_n: int = 30) -> List[int]:
        all_pos = [p for p in self._by_pos.get(pos, []) if p not in squad_set]
        scored  = [(_get_feats(self._cache, p, gw)[1]
                    + _get_feats(self._cache, p, gw)[8], p)
                   for p in all_pos]
        scored.sort(reverse=True)
        return [p for _, p in scored[:max_n]]
